import jsPDF from 'jspdf';

export const generatePDF = (explanation, language, complexity) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - (margin * 2);
    let y = 20;

    // Helper to add text and advance y
    const addText = (text, fontSize = 12, fontType = 'normal', color = [0, 0, 0]) => {
        if (!text) return;
        
        doc.setFontSize(fontSize);
        doc.setFont('helvetica', fontType);
        doc.setTextColor(...color);
        
        // Split text to fit width
        const lines = doc.splitTextToSize(text, contentWidth);
        
        // PAGE BREAK CHECK
        if (y + (lines.length * fontSize * 0.5) > doc.internal.pageSize.getHeight() - margin) {
            doc.addPage();
            y = 20;
        }

        doc.text(lines, margin, y);
        y += (lines.length * fontSize * 0.45) + 5; // Line height + spacing
    };

    // --- Header ---
    addText("DevPain AI - Code Analysis", 22, 'bold', [88, 166, 255]); // Accent color
    y += 5;
    addText(`Language: ${language} | Mode: ${complexity}`, 10, 'normal', [100, 100, 100]);
    y += 10;
    
    // --- Line separator ---
    doc.setLineWidth(0.5);
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y - 5, pageWidth - margin, y - 5);

    // --- Sections ---

    if (explanation.summary) {
        addText("1. What this code does", 14, 'bold');
        addText(explanation.summary);
        y += 5;
    }

    if (explanation.lineByLine) {
        addText("2. Line-by-line Explanation", 14, 'bold');
        addText(explanation.lineByLine);
        y += 5;
    }

    if (explanation.logicFlow) {
        addText("3. Logic Flow", 14, 'bold');
        addText(explanation.logicFlow);
        y += 5;
    }

    if (explanation.issues) {
        addText("4. Potential Issues & Bad Practices", 14, 'bold', [200, 50, 50]);
        addText(explanation.issues);
        y += 5;
    }

    if (explanation.improvedVersion) {
        addText("5. Improved Version", 14, 'bold');
        doc.setFont('courier', 'normal'); // Monospace for code
        doc.setFillColor(245, 245, 245);
        
        // Estimate height for background rect
        const codeLines = doc.splitTextToSize(explanation.improvedVersion, contentWidth - 10);
        const codeHeight = (codeLines.length * 10 * 0.5) + 10;
        
        if (y + codeHeight > doc.internal.pageSize.getHeight() - margin) {
            doc.addPage();
            y = 20;
        }
        
        doc.rect(margin, y, contentWidth, codeHeight, 'F');
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(10);
        doc.text(codeLines, margin + 5, y + 7);
        y += codeHeight + 10;
    }

    // --- Footer ---
    const pageCount = doc.internal.getNumberOfPages();
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Generated by DevPain AI - Page ${i} of ${pageCount}`, margin, doc.internal.pageSize.getHeight() - 10);
    }

    doc.save(`devpain-explanation-${Date.now()}.pdf`);
};
